# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'PlaceAVoteApp' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket', 'ART', 'RCTLinkingIOS’,  'RCTVibration’,  'RCTSettings’,  'RCTGeolocation’,  'RCTActionSheet’], :path => '../node_modules/react-native'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
end

target 'PlaceAVoteAppTests' do
end
